# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-12 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Passengers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainName', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('doc_image', models.ImageField(blank=True, default=b'default.png', upload_to=b'')),
            ],
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
